version: "2"
run:
  build-tags:
    - smoke
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - errcheck
    - funlen
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: log
            - pkg: github.com/davecgh/go-spew
            - pkg: github.com/cenkalti/backof[f]
              desc: use github.com/cenkalti/backoff/v4 instead
            - pkg: gotest.tools/assert
              desc: use gotest.tools/v3/assert instead
            - pkg: gotest.tools/assert/cmp
              desc: use gotest.tools/v3/assert/cmp instead
            - pkg: gotest.tools/env
              desc: use gotest.tools/v3/env instead
            - pkg: gotest.tools/fs
              desc: use gotest.tools/v3/fs instead
            - pkg: gotest.tools/golden
              desc: use gotest.tools/v3/golden instead
            - pkg: gotest.tools/icmd
              desc: use gotest.tools/v3/icmd instead
            - pkg: gotest.tools/poll
              desc: use gotest.tools/v3/poll instead
            - pkg: gotest.tools/skip
              desc: use gotest.tools/v3/skip instead
    dupl:
      threshold: 100
    funlen:
      lines: 80
    goconst:
      min-len: 6
      min-occurrences: 8
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
    nakedret:
      max-func-lines: 0
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        text: G104
      - linters:
          - gosec
        path: _test\.go
        text: G601
      - linters:
          - gosec
        path: _test\.go
        text: G107
      - linters:
          - revive
        text: 'package-comments: should have a package comment'
      - linters:
          - staticcheck
        path: _test\.go
        text: SA5011
      - linters:
          - staticcheck
        text: SA5001
      - linters:
          - staticcheck
        text: ST1003
      - linters:
          - golint
        text: should have( a package)? comment
      - linters:
          - lll
        source: https?://
      - linters:
          - lll
        source: '"message":'
      - linters:
          - lll
        source: help:"
      - linters:
          - errcheck
        source: ^\s*defer .*\.Close(.*)$
      - linters:
          - funlen
        text: ^Function 'Test.*
      - linters:
          - funlen
        text: ^Function 'runServices.*
      - linters:
          - staticcheck
        text: ST1000
      - linters:
          - unparam
        path: _test\.go
      - linters:
          - revive
        text: 'exported:'
      - linters:
          - ineffassign
        text: ineffectual assignment to ctx
      - linters:
          - staticcheck
        text: 'SA4006: this value of `ctx` is never used'
      - linters:
          - gocyclo
        text: func `TestE2E.*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/circleci/runner-init)
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/circleci/runner-init
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
