version: 2.1
workflows:
  webhook:
    jobs:
      - trigger-workflow
jobs:
  trigger-workflow:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Filter only agent tagged images
          command: |
            export IMAGE_TAG="$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq .push_data.tag)"

            # If workflow is triggered by a webhook, verify it was for a new "agent" tag for task-agent
            if [[ "<< pipeline.trigger_source >>" = "webhook" ]]; then
              # Halt the step if it wasn't triggered for a new "agent" image build on task-agent
              if [[ ! "$IMAGE_TAG" = '"agent"' ]]; then
                echo "Step halted because the image tag is not 'agent'."
                circleci-agent step halt
              fi
            else
              # We should never get here by automation, but just in case
              echo "Step halted because the pipeline was not triggered by a webhook."
              circleci-agent step halt
            fi
      - run:
          name: Trigger Image Rebuild
          command: |
            curl -X POST "https://circleci.com/api/v2/project/github/circleci/runner-init/pipeline" \
              --header "Circle-Token: $WEBHOOK_CCI_API_TOKEN" \
              --header "Content-Type: application/json" \
              -data '{"parameters": {"triggered_by_webhook": true}}'
