version: 2.1
workflows:
  webhook:
    jobs:
      - filter-webhook
      - trigger-workflow:
          requires: [ filter-webhook ]
jobs:
  filter-webhook:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Filter Only Agent Tagged Images
          command: |
            export IMAGE_TAG="$(echo << pipeline.trigger_parameters.webhook.body >> | jq .push_data.tag)"
             # if workflow is trigged by a webhook verify it was for a new "agent" tag for task-agent
            if [[ "<< pipeline.trigger_source >>" = "webhook" ]];
            # cancel workflow if it wasn't triggered for a new "agent" image build on task-agent
              if [[ ! "$IMAGE_TAG" = "agent" ]];
                curl --request POST \
                  --url "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel" \
                  --header "Circle-Token: ${WEBHOOK_CCI_API_TOKEN}"
              fi
            else
              # we should never get here by automation, but just incase
              curl --request POST \
                --url "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel" \
                --header "Circle-Token: ${WEBHOOK_CCI_API_TOKEN}"
            fi

  trigger-workflow:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Trigger Image Rebuild
          command: |
            curl -X POST "https://circleci.com/api/v2/project/runner-init/pipeline" \
              --data '{"branch" : "main"}'
              --header 'content-type: application/json'
              --header "authorization: Basic $WEBHOOK_CCI_API_TOKEN"

